name: daily-commit

on:
  schedule:
    - cron: '35 02 * * *'  # Every day at 05:30 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Make a change using 24f2003023@ds.study.iitm.ac.in
        run: echo "Updated on $(date)" > daily.txt

      - name: Commit and Push Changes
        run: |
          git config user.name "Auto Commit Bot"
          git config user.email "24f2007248@ds.study.iitm.ac.in"
          git add .
          git commit -m "Daily update $(date)" || echo "No changes to commit"
          git push
